/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e2dfff',
        'surface-container': '#e5eeff',
        'tertiary': '#7e3000',
        'tertiary-fixed': '#ffdbcc',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed-dim': '#c3c0ff',
        'secondary-container': '#dae2fd',
        'surface-tint': '#4d44e3',
        'inverse-primary': '#c3c0ff',
        'on-error-container': '#93000a',
        'outline-variant': '#c7c4d8',
        'on-surface': '#0b1c30',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'tertiary-fixed-dim': '#ffb695',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#3323cc',
        'surface-bright': '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'secondary-fixed': '#dae2fd',
        'on-primary-fixed': '#0f0069',
        'tertiary-container': '#a44100',
        'surface-container-low': '#eff4ff',
        'secondary-fixed-dim': '#bec6e0',
        'on-surface-variant': '#464555',
        'on-background': '#0b1c30',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#ffd2be',
        'on-secondary-fixed': '#131b2e',
        'primary-container': '#4f46e5',
        'on-secondary-container': '#5c647a',
        'on-primary-container': '#dad7ff',
        'primary': '#3525cd',
        'surface-container-lowest': '#ffffff',
        'outline': '#777587',
        'surface-dim': '#cbdbf5',
        'on-error': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'surface': '#f8f9ff',
        'inverse-surface': '#213145',
        'on-tertiary-fixed': '#351000',
        'on-secondary-fixed-variant': '#3f465c',
        'on-tertiary': '#ffffff',
        'background': '#f8f9ff',
        'secondary': '#565e74',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '32px',
        'container-max': '1200px',
        'section-gap': '120px',
        'base': '4px',
        'stack-md': '16px',
        'gutter': '24px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        display: ['Geist', 'sans-serif'],
        code: ['monospace'],
        'headline-lg': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'display-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        code: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '1.2', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
